services:
  db:
    image: "postgres:13"
    environment:
      - POSTGRES_DB=TooManyChoco
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data:rw

volumes:
  db:
